version: 2
builds:
  - main: ./cmd/portfwd
    binary: portfwd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
upx:
  - enabled: true
checksum:
  name_template: checksums.txt
source:
  enabled: true
sboms:
  - artifacts: source
release:
  prerelease: auto
  skip_upload: true
changelog:
  use: github
  filters:
    exclude:
      - merge conflict
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
dockers:
  - dockerfile: goreleaser.Dockerfile
    image_templates:
      - ghcr.io/frantjc/port-forward:{{ .Version }}
      - ghcr.io/frantjc/port-forward:{{ .Major }}.{{ .Minor }}
      - ghcr.io/frantjc/port-forward:{{ .Major }}
      - ghcr.io/frantjc/port-forward:latest
    build_flag_templates:
      - --pull
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --platform=linux/amd64
docker_signs:
  - cmd: cosign
    artifacts: images
    args:
      - "sign"
      - "${artifact}"
      - "--yes"
    output: true
