apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: port-forward
    app.kubernetes.io/managed-by: kustomize
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: port-forward
    app.kubernetes.io/managed-by: kustomize
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      control-plane: controller-manager
      app.kubernetes.io/name: port-forward
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
        app.kubernetes.io/name: port-forward
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
      hostNetwork: true
      containers:
        - image: ghcr.io/frantjc/port-forward:0.1.7
          args:
            - --leader-elect
            - --health-probe-bind-address=:8081
          name: port-forward
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 5m
              memory: 64Mi
            limits:
              cpu: 10m
              memory: 128Mi
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
