---
apiVersion: v1
kind: Service
metadata:
  name: sample
  annotations:
    pf.frantj.cc/forward: "yes"
    pf.frantj.cc/port-map: 0:443,80:3000
	  upnp.pf.frantj.cc/remote-host: sample
	  upnp.pf.frantj.cc/enabled: "true"
	  upnp.pf.frantj.cc/description: port-forward
	  upnp.pf.frantj.cc/lease-duration: 1h
spec:
  type: LoadBalancer
  ports:
    - name: simple
      port: 80
      targetPort: 6666
    - name: excluded
      port: 443
      targetPort: 7777
    - name: remapped
      port: 3000
      targetPort: 8888
  selector: {}
